### successful POST req to login
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "ptr",
  "password": "stylin"
}

### unsuccessful POST req to login, invalid password
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "ptr",
  "password": "invalid"
}

### unsuccessful POST req to login, invalid username
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "ptt",
  "password": "stylin"
}
